In [3]:
import numpy as np
a = np.array([5,2,1,5,6,8])

In [5]:
b = a.reshape([3,2])
b

array([[5, 2],
       [1, 5],
       [6, 8]])

In [7]:
c = np.zeros((4,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.random.seed(0)
r = np.random.rand(3,4)
r

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])